Vagrant.configure("2") do |config|

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "linux-k8s"
      node.vm.hostname = "linux-generic-#{i}"
      node.vm.box_check_update=false
      node.vm.network "private_network", ip: "192.168.200.20#{i}"
    end
  end


end
