Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "linux-generic"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.200.200"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "linux-generic"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.200.201"
  end

end
